from pathlib import Path
from fpdf import FPDF


def clean_for_pdf(text: str) -> str:
    """
    Convert common Unicode characters generated by AI
    into characters supported by standard PDF fonts.
    """

    replacements = {
        "\u2010": "-",    # Hyphen
        "\u2011": "-",    # Non-breaking hyphen
        "\u2012": "-",    # Figure dash
        "\u2013": "-",    # En dash
        "\u2014": "-",    # Em dash
        "\u2015": "-",    # Horizontal bar

        "\u2018": "'",    # Left single quotation mark
        "\u2019": "'",    # Right single quotation mark
        "\u201a": "'",    # Single low-9 quotation mark

        "\u201c": '"',    # Left double quotation mark
        "\u201d": '"',    # Right double quotation mark
        "\u201e": '"',    # Double low-9 quotation mark

        "\u2026": "...",  # Ellipsis

        "\u00a0": " ",    # Non-breaking space
        "\u202f": " ",    # Narrow no-break space

        "\u2009": " ",    # Thin space
        "\u2002": " ",    # En space
        "\u2003": " ",    # Em space
        "\u2004": " ",    # Three-per-em space
        "\u2005": " ",    # Four-per-em space
        "\u2006": " ",    # Six-per-em space
        "\u2007": " ",    # Figure space
        "\u2008": " ",    # Punctuation space
        "\u200a": " ",    # Hair space
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text


def create_board_report(
    output_path: str,
    total_transactions: int,
    suspicious_transactions: int,
    anomalous_transactions: int,
    suspicious_details: str,
    anomaly_details: str,
    insight: str,
):
    pdf = FPDF()

    pdf.set_auto_page_break(
        auto=True,
        margin=15
    )

    pdf.add_page()

    # -------------------------------------------------
    # TITLE
    # -------------------------------------------------

    pdf.set_font("Arial", "B", 18)

    pdf.cell(
        0,
        12,
        "CFO NIGHT SHIFT",
        ln=True,
        align="C",
    )

    pdf.set_font("Arial", "B", 14)

    pdf.cell(
        0,
        10,
        "Financial Monitoring Report",
        ln=True,
        align="C",
    )

    pdf.ln(8)

    # -------------------------------------------------
    # MONITORING OVERVIEW
    # -------------------------------------------------

    pdf.set_font("Arial", "B", 12)

    pdf.cell(
        0,
        8,
        "1. Monitoring Overview",
        ln=True,
    )

    pdf.set_font("Arial", "", 11)

    overview = (
        f"Total transactions reviewed: {total_transactions}\n"
        f"Suspicious transactions: {suspicious_transactions}\n"
        f"Anomalous transactions: {anomalous_transactions}"
    )

    pdf.multi_cell(
        0,
        7,
        overview,
    )

    pdf.ln(5)

    # -------------------------------------------------
    # SUSPICIOUS TRANSACTIONS
    # -------------------------------------------------

    pdf.set_font("Arial", "B", 12)

    pdf.cell(
        0,
        8,
        "2. Suspicious Transactions",
        ln=True,
    )

    pdf.set_font("Courier", "", 8)

    safe_suspicious_details = clean_for_pdf(
        suspicious_details
    )

    pdf.multi_cell(
        0,
        5,
        safe_suspicious_details,
    )

    pdf.ln(5)

    # -------------------------------------------------
    # EXPENSE ANOMALIES
    # -------------------------------------------------

    pdf.set_font("Arial", "B", 12)

    pdf.cell(
        0,
        8,
        "3. Expense Anomalies",
        ln=True,
    )

    pdf.set_font("Courier", "", 8)

    safe_anomaly_details = clean_for_pdf(
        anomaly_details
    )

    pdf.multi_cell(
        0,
        5,
        safe_anomaly_details,
    )

    pdf.ln(5)

    # -------------------------------------------------
    # CFO INSIGHT
    # -------------------------------------------------

    pdf.set_font("Arial", "B", 12)

    pdf.cell(
        0,
        8,
        "4. CFO Insight",
        ln=True,
    )

    pdf.set_font("Arial", "", 10)

    safe_insight = clean_for_pdf(
        insight
    )

    pdf.multi_cell(
        0,
        6,
        safe_insight,
    )

    pdf.ln(5)

    # -------------------------------------------------
    # HUMAN REVIEW DISCLAIMER
    # -------------------------------------------------

    pdf.set_font("Arial", "I", 9)

    disclaimer = (
        "Note: Flagged transactions require human investigation. "
        "Automated detection does not establish fraud or wrongdoing."
    )

    pdf.multi_cell(
        0,
        5,
        disclaimer,
    )

    # -------------------------------------------------
    # SAVE REPORT
    # -------------------------------------------------

    Path(output_path).parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    pdf.output(output_path)

    return output_path